baseurl = "/"
languageCode = "en-us"
title = "Data land"
# Enable comments by entering your Disqus shortname
disqusShortname = "filipwastberg"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "â†©"
theme = "hugo-icarus-theme"
favicon = "css/images/logo2.png"
# Comment the themesDir option if you use this theme in production


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Data land"
    bio = "En blogg om data-analys i R."
    location = "Sweden"
    site_description = "En blogg om data-analys i R."
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/fwg.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = ""
    logo = "css/images/logo2.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Hem"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Taggar"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Kategorier"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/filipwastberg"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "filipwastberg"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "filipwastberg"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = false
    tag_cloud = false
